services:
  database:
    container_name: rust-learning-db
    image: postgres
    #   restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      retries: 5
      # let time for the db to start
      start_period: 10s
      timeout: 10s
  api:
    container_name: rust-learning
    image: rust-learning
    environment:
      APP_ENVIRONMENT: production
      APP_DATABASE_HOST: DATABASE
      APP_DATABASE_USERNAME: ${DB_USER}
      APP_DATABASE_PASSWORD: ${DB_PASS}
      APP_DATABASE_DATABASE_NAME: ${DB_NAME}
      APP_DATABASE_PORT: 5432
      APP_DATABASE_DEBUG: "true"
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      database:
        # start the service when db is ready through healthcheck
        condition: service_healthy