name: rust-learning
services:
  database:
    container_name: cyberpal_postgres
    image: postgres
    #   restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      retries: 5
      # let time for the db to start
      start_period: 10s
      timeout: 10s
  api:
    container_name: rust-learning
    image: rust-learning
    env_file:
      - .env
    environment:
      APP_DATABASE__DATABASE_HOST: database
      APP_DATABASE__DATABASE_USER: ${DB_USER}
      APP_DATABASE__DATABASE_PASSWORD: ${DB_PASS}
      APP_DATABASE__DATABASE_NAME: ${DB_NAME}
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      database:
        # start the service when db is ready through healthcheck
        condition: service_healthy