redis_uri: "redis://127.0.0.1:6379"
application:
  port: 8000
  hmac_secret: "Backside7-Deceptive4-Overboard6-Violation3-Bulginess2-Manned0-Grumble6-Retouch7-Comma8-Proton2"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "my-secret_token"
  timeout_milliseconds: 10000
